import type { Metadata } from "next";
import "./ui/globals.css";
import { montserrat } from '@/app/ui/fonts'
import { Header } from "./components/Header"
import Image from "next/image";
import { MovimientosProvider } from "@/context/MovimientosContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-MX">
      <body
        className={`${montserrat.className} $antialiased`}
      >
        <Header/>
        <main>
          <MovimientosProvider>
          {children}
          </MovimientosProvider>
        </main>
        <footer className="flex justify-center items-center space-x-4">
          <p className="mt-10">Propiedad de</p>
          <Image width="70" height="50" src="/logo_guna.png" alt='Logo Guna'/>
        </footer>
      </body>
    </html>
  );
}
